#Workflow name
name: Build Spring Boot application with GitHub Actions
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  # Build's job
  build:
    name: Build the application
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
     # Checkout code
     - uses: actions/checkout@v2
     # Setup Java
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt' # See 'Supported distributions' for available options
         java-version: '11'
         cache: 'maven'
         server-id: ghcr.io
         server-username: ${{secrets.DOCKER_USERNAME}}
         server-password: ${{secrets.DOCKER_PASSWORD}}
     # Build Spring boot
     - name: Build the project
       run: mvn -B -DskipTests install
     # Build Docker image  
     - name: Build Docker
       run: mvn jib:build
       env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
